// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfYrhi3UdwhNoI9VHS87-sbon0Vcn0C9g',
    appId: '1:13676468434:web:22b8180da6594b54efb50b',
    messagingSenderId: '13676468434',
    projectId: 'flutterlearn-da969',
    authDomain: 'flutterlearn-da969.firebaseapp.com',
    databaseURL:
        'https://flutterlearn-da969-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterlearn-da969.appspot.com',
    measurementId: 'G-BXSKJ0SJTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKb2-aEPhO_ttAW07iqKCCunWtbKsEVns',
    appId: '1:13676468434:android:ff4cefbd72376187efb50b',
    messagingSenderId: '13676468434',
    projectId: 'flutterlearn-da969',
    databaseURL:
        'https://flutterlearn-da969-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterlearn-da969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExOp1GroLX7_kGaJwD5g92-76tUlG4vE',
    appId: '1:13676468434:ios:7804d122256ee412efb50b',
    messagingSenderId: '13676468434',
    projectId: 'flutterlearn-da969',
    databaseURL:
        'https://flutterlearn-da969-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterlearn-da969.appspot.com',
    iosClientId:
        '13676468434-d2nfk3cjrsqqcira203b0uk713u16f9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDExOp1GroLX7_kGaJwD5g92-76tUlG4vE',
    appId: '1:13676468434:ios:7804d122256ee412efb50b',
    messagingSenderId: '13676468434',
    projectId: 'flutterlearn-da969',
    databaseURL:
        'https://flutterlearn-da969-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterlearn-da969.appspot.com',
    iosClientId:
        '13676468434-d2nfk3cjrsqqcira203b0uk713u16f9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutter',
  );
}
